### ISSUE TITLE
Deployment – ​​Tested and documented campaign feature process

### ISSUE THREAD

**Issue by mmarchal** [XPEHO/xpeapp_admin#88]

**Comment by lcubeddu** [comment]
https://yaki.xpeho.fr/bookstack/books/xpeapp/page/process-creer-et-modifier-une-campagne

Est-ce que c'est ce que tu voulais @mmarchal ?

**Comment by mmarchal** [comment]
@lcubeddu Il manque juste une petite info : lorsqu'une campagne est archivé, il y a une popup pour ajouter un commentaire qui sera l'action à faire. Sinon parfait ;)

**Comment by lcubeddu** [comment]
@mmarchal j'ai testé sur la branche main actuelle, et j'ai dû spam de nombreuses fois afin que l'archive se fasse. Ensuite, toutes les archives ont `Commentaire :` d'affiché, sans qu'il n'y ait de commentaire (dont celle que j'ai close avec un commentaire).

Donc de mon coté c'est cassé. J'ai quand même update le bookstack.

**Comment by mmarchal** [comment]
@lcubeddu J'ai trouvé le soucis lié à l'ajout d'un commentaire.
Je vais faire une PR pour corriger ça
